"""
Q-Ravens State Schema

Defines the shared state that flows between all agents in the workflow.
This is the central data structure for LangGraph orchestration.
"""

from datetime import datetime
from enum import Enum
from typing import Annotated, Any, Optional, TypedDict

from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage
from pydantic import BaseModel, Field


class WorkflowPhase(str, Enum):
    """Current phase in the testing workflow."""

    INIT = "init"
    ANALYZING = "analyzing"
    DESIGNING = "designing"
    EXECUTING = "executing"
    REPORTING = "reporting"
    COMPLETED = "completed"
    ERROR = "error"
    WAITING_FOR_USER = "waiting_for_user"


class TestStatus(str, Enum):
    """Status of individual test cases."""

    PENDING = "pending"
    RUNNING = "running"
    PASSED = "passed"
    FAILED = "failed"
    SKIPPED = "skipped"
    ERROR = "error"


class PageInfo(BaseModel):
    """Information about a discovered page."""

    url: str
    title: Optional[str] = None
    links: list[str] = Field(default_factory=list)
    forms: list[dict[str, Any]] = Field(default_factory=list)
    buttons: list[str] = Field(default_factory=list)
    inputs: list[dict[str, Any]] = Field(default_factory=list)


class AnalysisResult(BaseModel):
    """Results from the Analyzer agent."""

    target_url: str
    pages_discovered: list[PageInfo] = Field(default_factory=list)
    technology_stack: list[str] = Field(default_factory=list)
    has_authentication: bool = False
    auth_type: Optional[str] = None
    sitemap: dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=datetime.now)


class TestCase(BaseModel):
    """A single test case designed by the Designer agent."""

    id: str
    name: str
    description: str
    steps: list[str] = Field(default_factory=list)
    expected_result: str
    priority: str = "medium"  # high, medium, low
    category: str = "functional"  # functional, accessibility, performance
    status: TestStatus = TestStatus.PENDING


class TestResult(BaseModel):
    """Result of executing a test case."""

    test_id: str
    status: TestStatus
    actual_result: Optional[str] = None
    error_message: Optional[str] = None
    screenshot_path: Optional[str] = None
    duration_ms: int = 0
    timestamp: datetime = Field(default_factory=datetime.now)


class ReportFormat(str, Enum):
    """Supported report output formats."""

    MARKDOWN = "markdown"
    HTML = "html"
    JSON = "json"


class TestSummary(BaseModel):
    """Summary statistics for test execution."""

    total_tests: int = 0
    passed: int = 0
    failed: int = 0
    skipped: int = 0
    errors: int = 0
    pass_rate: float = 0.0
    total_duration_ms: int = 0


class TestReport(BaseModel):
    """Complete test report generated by the Reporter agent."""

    # Report metadata
    report_id: str
    title: str
    generated_at: datetime = Field(default_factory=datetime.now)
    format: ReportFormat = ReportFormat.MARKDOWN

    # Target information
    target_url: str
    user_request: Optional[str] = None

    # Executive summary (non-technical)
    executive_summary: str = ""

    # Test summary statistics
    summary: TestSummary = Field(default_factory=TestSummary)

    # Detailed findings
    critical_issues: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    recommendations: list[str] = Field(default_factory=list)

    # Test details
    test_details: list[dict[str, Any]] = Field(default_factory=list)

    # Raw content for different formats
    markdown_content: Optional[str] = None
    html_content: Optional[str] = None
    json_content: Optional[str] = None


class QRavensState(TypedDict, total=False):
    """
    The main state object passed between all agents.

    This follows LangGraph patterns for stateful workflows using TypedDict.
    """

    # User Input
    target_url: str
    user_request: str

    # Conversation history (uses LangGraph's message reducer)
    messages: Annotated[list[BaseMessage], add_messages]

    # Workflow Control
    phase: str  # WorkflowPhase value
    current_agent: str
    next_agent: str
    iteration_count: int
    max_iterations: int

    # Analysis Results (from Analyzer)
    analysis: AnalysisResult

    # Test Cases (from Designer)
    test_cases: list[TestCase]

    # Test Results (from Executor)
    test_results: list[TestResult]

    # Report (from Reporter)
    report: TestReport

    # Error Handling
    errors: list[str]

    # Human-in-the-loop
    requires_user_input: bool
    user_input_prompt: str
    user_input: str  # The actual user input value
    approval_request: dict  # Request details for approval
    approval_response: dict  # User's response to approval request

    # Metadata
    session_id: str
    started_at: str

    # LLM Configuration (passed from UI)
    llm_provider: str  # LLMProvider value
    llm_model: str
    llm_api_key: str
